Docs
nivinjoseph/n-app pull request #12
Opened 2021-07-13 15:18 UTC by BenjaminSao

2021-08-13 16:56 UTC, shreymahendru requested changes

2021-08-13 16:56 UTC, shreymahendru commented on README.md
> +**n-app** allows for Vue operations with the DOM with **separation of concern**. Instead of writing the methods, data and template inside one file, you are able to separate it into a template file (*
This section should be at the very top, where you are explaining how to structure

2021-08-13 16:56 UTC, shreymahendru commented on README.md
> +Inside your **TypeScript** view-model file and inside the class, you'll create a method:
a public method

2021-08-13 16:56 UTC, shreymahendru commented on README.md
> +You can easily incorporate **Vue's** data binding like this:
Just say data binding is similar to vue

2021-08-13 16:56 UTC, shreymahendru commented on README.md
> +**Note:** It is **extremely** important to `unsubscribe` from any `EventSubscription` once you've finished using it. This is usually called on the `onLeave` lifecycle method or `onDismount` for persi
Why is it important? otherwise you will have a memory leak

2021-08-13 16:56 UTC, shreymahendru commented on README.md
> +Navigation service allows you to take advantage of **Vue's router-enabled application architecture**.
router-enabled application architecture?  what is that?

2021-08-13 16:56 UTC, shreymahendru commented on README.md
> +Now we're done!
No, you are not done yet, you forgot the most important part, the client.ts file where everything comes together

2021-08-17 15:44 UTC, BenjaminSao commented on src/services/navigation-service/navigation-service.ts
> +     */
Yes, it does.

2021-08-17 15:59 UTC, BenjaminSao commented on README.md
> +export class Page1ViewModel extends PageViewModel // Inheriting the PageViewModel class
I already did line 248 and line 239.

2021-08-17 15:59 UTC, BenjaminSao commented on README.md
> +export class Page1ViewModel extends PageViewModel // Inheriting the PageViewModel class
I haven't talked about ComponentViewModel because I speak about it later on.

2022-03-15 00:47 UTC, merged